name: fba
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - python==3.6
  - dnaio
  - hdbscan==0.8.21
  - matplotlib==3.3
  - numpy==1.19.0
  - pandas==1.0.0
  - polyleven==0.5
  - pyclustering==0.10.1
  - pysam==0.14.0
  - scikit-learn==0.23.0
  - scipy==1.5.0
  - statsmodels==0.11.1
  - umap-learn
  - umi_tools==1.0.0
  - samtools
  - seaborn==0.10.0
  - bowtie2==2.4.0
  - bwa==0.7.0
