version: 2.1

orbs:
  python: circleci/python@1.3.4

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements.txt
      - run:
        name: Install flake8 pytest
        command: |
          python -m pip install flake8 pytes


workflows:
  main:
    jobs:
      - build-and-test
