version: 2.1

orbs:
  python: circleci/python@1.3.4

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - run:
        name: Install dependencies
        command: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi




workflows:
  main:
    jobs:
      - build-and-test
